version: "3.1"

services:
    server:
        env_file:
            - server/env
        volumes:
            - ../config.php:/var/www/html/config.php
            - ./server/config.email-secrets.php:/var/www/html/application/config/email.php
