version: "3.1"

services:
  server:
    secrets:
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASS
      - SMTP_CRYPTO
      - SMTP_PORT

secrets:
  SMTP_HOST:
    file: secrets/SMTP_HOST
  SMTP_USER:
    file: secrets/SMTP_USER
  SMTP_PASS:
    file: secrets/SMTP_PASS
  SMTP_CRYPTO:
    file: secrets/SMTP_CRYPTO
  SMTP_PORT:
    file: secrets/SMTP_PORT
