version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        restart: unless-stopped
        
    server:
        depends_on:
            - mysql
        links:
            - mysql
        build:
            context: ..
            dockerfile: docker/server/Dockerfile
        image: easyappointments-server:v1
        container_name: easyappointments-server
        restart: unless-stopped
        volumes:
            - ../application:/var/www/html/application
            - ../engine:/var/www/html/engine
            - ../assets:/var/www/html/assets
