version: "3.1"

services:
  server:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.booking-test.entryPoints=web,websecure"
      - "traefik.http.routers.booking-test.rule=Host(`booking.test.vanhack.ca`)"
      - "traefik.http.routers.booking-test.tls=true"
      - "traefik.http.routers.booking-test.tls.certresolver=lets-encrypt"
